// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ModuleAC
List ModuleAC(const List& parameters_arg);
RcppExport SEXP _MedianaADT_ModuleAC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ModuleAC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ModuleBC
List ModuleBC(const List& parameters_arg);
RcppExport SEXP _MedianaADT_ModuleBC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ModuleBC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ModuleCC
List ModuleCC(const List& parameters_arg);
RcppExport SEXP _MedianaADT_ModuleCC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ModuleCC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ModuleDC
List ModuleDC(const List& parameters_arg);
RcppExport SEXP _MedianaADT_ModuleDC(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ModuleDC(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}
// ModuleEEventCount
List ModuleEEventCount(const List& parameters_arg);
RcppExport SEXP _MedianaADT_ModuleEEventCount(SEXP parameters_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type parameters_arg(parameters_argSEXP);
    rcpp_result_gen = Rcpp::wrap(ModuleEEventCount(parameters_arg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MedianaADT_ModuleAC", (DL_FUNC) &_MedianaADT_ModuleAC, 1},
    {"_MedianaADT_ModuleBC", (DL_FUNC) &_MedianaADT_ModuleBC, 1},
    {"_MedianaADT_ModuleCC", (DL_FUNC) &_MedianaADT_ModuleCC, 1},
    {"_MedianaADT_ModuleDC", (DL_FUNC) &_MedianaADT_ModuleDC, 1},
    {"_MedianaADT_ModuleEEventCount", (DL_FUNC) &_MedianaADT_ModuleEEventCount, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MedianaADT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
