# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ModuleAC <- function(parameters_arg) {
    .Call(`_MedianaADT_ModuleAC`, parameters_arg)
}

ModuleBC <- function(parameters_arg) {
    .Call(`_MedianaADT_ModuleBC`, parameters_arg)
}

ModuleCC <- function(parameters_arg) {
    .Call(`_MedianaADT_ModuleCC`, parameters_arg)
}

ModuleDC <- function(parameters_arg) {
    .Call(`_MedianaADT_ModuleDC`, parameters_arg)
}

ModuleEEventCount <- function(parameters_arg) {
    .Call(`_MedianaADT_ModuleEEventCount`, parameters_arg)
}

